let itemData = [
    {
        name: "Smartphone X",
        description: "A high-end smartphone with advanced features.",
        category: "Electronics",
        price: 799,
        quantity: 50,
      },
      {
        name: "Smartphone X",
        description: "A high-end smartphone with advanced features.",
        category: "Electronics",
        price: 799,
        quantity: 50,
      },
      {
        name: "Laptop Pro",
        description: "A powerful laptop for professional use.",
        category: "Electronics",
        price: 1299,
        quantity: 30,
      },
      {
        name: "LED TV 55",
        description: "A 55-inch LED TV with 4K resolution.",
        category: "Electronics",
        price: 899,
        quantity: 20,
      },
      {
        name: "Wireless Headphones",
        description: "Bluetooth headphones with noise-cancellation.",
        category: "Electronics",
        price: 149,
        quantity: 100,
      },
      {
        name: "Smartwatch Lite",
        description: "A lightweight smartwatch with fitness tracking.",
        category: "Electronics",
        price: 199,
        quantity: 80,
      },
      {
        name: "Men's Casual Shirt",
        description: "A comfortable shirt for everyday wear.",
        category: "Clothing",
        price: 29.99,
        quantity: 200,
      },
      {
        name: "Women's Summer Dress",
        description: "A stylish dress for summer outings.",
        category: "Clothing",
        price: 49.99,
        quantity: 150,
      },
      {
        name: "Men's Formal Suit",
        description: "A classic suit for formal occasions.",
        category: "Clothing",
        price: 199.99,
        quantity: 100,
      },
      {
        name: "Women's Winter Coat",
        description: "A warm coat for the winter season.",
        category: "Clothing",
        price: 99.99,
        quantity: 120,
      },
      {
        name: "Unisex Sports Shoes",
        description: "Athletic shoes suitable for various sports.",
        category: "Clothing",
        price: 79.99,
        quantity: 180,
      },
      {
        name: "The Great Gatsby",
        description: "A classic novel by F. Scott Fitzgerald.",
        category: "Books",
        price: 12.99,
        quantity: 300,
      },
      {
        name: "Sapiens: A Brief History of Humankind",
        description: "A popular non-fiction book about human history.",
        category: "Books",
        price: 15.99,
        quantity: 250,
      },
      {
        name: "The Subtle Art of Not Giving a F*ck",
        description: "A self-help book about living a meaningful life.",
        category: "Books",
        price: 10.99,
        quantity: 200,
      },
      {
        name: "Educated",
        description: "A memoir by Tara Westover about her education.",
        category: "Books",
        price: 14.99,
        quantity: 180,
      },
      {
        name: "1984",
        description: "A dystopian novel by George Orwell.",
        category: "Books",
        price: 9.99,
        quantity: 350,
      },
      {
        name: "Stainless Steel Cookware Set",
        description: "A set of high-quality pots and pans.",
        category: "Home & Kitchen",
        price: 149.99,
        quantity: 100,
      },
      {
        name: "Robot Vacuum Cleaner",
        description: "An automated vacuum cleaner for effortless cleaning.",
        category: "Home & Kitchen",
        price: 249.99,
        quantity: 80,
      },
      {
        name: "Decorative Throw Pillows",
        description: "Soft pillows to add a decorative touch to your home.",
        category: "Home & Kitchen",
        price: 19.99,
        quantity: 200,
      },
      {
        name: "Coffee Maker with Grinder",
        description: "A coffee machine with a built-in grinder for fresh brews.",
        category: "Home & Kitchen",
        price: 99.99,
        quantity: 150,
      },
      {
        name: "Digital Kitchen Scale",
        description: "A precise scale for measuring ingredients in the kitchen.",
        category: "Home & Kitchen",
        price: 29.99,
        quantity: 120,
      },
      {
        name: "LEGO Classic Creative Bricks",
        description: "A set of LEGO bricks for creative building.",
        category: "Toys & Games",
        price: 24.99,
        quantity: 300,
      },
      {
        name: "Monopoly Classic Board Game",
        description: "The classic board game of buying, selling, and trading properties.",
        category: "Toys & Games",
        price: 19.99,
        quantity: 250,
      },
      {
        name: "Nerf N-Strike Elite Disruptor Blaster",
        description: "A Nerf blaster for exciting foam dart battles.",
        category: "Toys & Games",
        price: 14.99,
        quantity: 200,
      },
      {
        name: "Barbie Dreamhouse",
        description: "A dollhouse for imaginative play with Barbie dolls.",
        category: "Toys & Games",
        price: 199.99,
        quantity: 180,
      },
      {
        name: "Puzzle Mat with Storage Bag",
        description: "A puzzle mat for easy storage and organization of puzzles.",
        category: "Toys & Games",
        price: 12.99,
        quantity: 350,
      },
      {
        name: "Anti-Aging Serum",
        description: "A skincare serum to reduce signs of aging.",
        category: "Beauty & Health",
        price: 49.99,
        quantity: 100
      },
      {
        name: "Vitamin C Supplements",
        description: "Vitamin C capsules for immune support.",
        category: "Beauty & Health",
        price: 19.99,
        quantity: 200
      },
      {
        name: "Organic Shampoo",
        description: "A natural shampoo for healthy hair.",
        category: "Beauty & Health",
        price: 12.99,
        quantity: 150
      },
      {
        name: "Matte Lipstick",
        description: "Long-lasting lipstick with a matte finish.",
        category: "Beauty & Health",
        price: 9.99,
        quantity: 300
      },
      {
        name: "Protein Powder",
        description: "Whey protein powder for muscle recovery.",
        category: "Beauty & Health",
        price: 29.99,
        quantity: 120
      },
      {
        name: "Yoga Mat",
        description: "A durable mat for yoga and exercise.",
        category: "Sports & Outdoors",
        price: 24.99,
        quantity: 200
      },
      {
        name: "Camping Tent",
        description: "A spacious tent for outdoor camping.",
        category: "Sports & Outdoors",
        price: 149.99,
        quantity: 50
      },
      {
        name: "Basketball",
        description: "Official size basketball for outdoor games.",
        category: "Sports & Outdoors",
        price: 29.99,
        quantity: 100
      },
      {
        name: "Hiking Backpack",
        description: "A comfortable backpack for hiking trips.",
        category: "Sports & Outdoors",
        price: 79.99,
        quantity: 80
      },
      {
        name: "Running Shoes",
        description: "High-performance shoes for running and sports.",
        category: "Sports & Outdoors",
        price: 99.99,
        quantity: 150
      },
];
module.exports = itemData; 
